// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Undermoon) DeepCopyInto(out *Undermoon) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Undermoon.
func (in *Undermoon) DeepCopy() *Undermoon {
	if in == nil {
		return nil
	}
	out := new(Undermoon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Undermoon) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UndermoonList) DeepCopyInto(out *UndermoonList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Undermoon, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UndermoonList.
func (in *UndermoonList) DeepCopy() *UndermoonList {
	if in == nil {
		return nil
	}
	out := new(UndermoonList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UndermoonList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UndermoonSpec) DeepCopyInto(out *UndermoonSpec) {
	*out = *in
	in.BrokerResources.DeepCopyInto(&out.BrokerResources)
	in.CoordinatorResources.DeepCopyInto(&out.CoordinatorResources)
	in.ProxyResources.DeepCopyInto(&out.ProxyResources)
	in.RedisResources.DeepCopyInto(&out.RedisResources)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UndermoonSpec.
func (in *UndermoonSpec) DeepCopy() *UndermoonSpec {
	if in == nil {
		return nil
	}
	out := new(UndermoonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UndermoonStatus) DeepCopyInto(out *UndermoonStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UndermoonStatus.
func (in *UndermoonStatus) DeepCopy() *UndermoonStatus {
	if in == nil {
		return nil
	}
	out := new(UndermoonStatus)
	in.DeepCopyInto(out)
	return out
}
