apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: undermoons.undermoon.operator.api
spec:
  group: undermoon.operator.api
  names:
    kind: Undermoon
    listKind: UndermoonList
    plural: undermoons
    singular: undermoon
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Undermoon is the Schema for the undermoons API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: UndermoonSpec defines the desired state of Undermoon
          properties:
            chunkNumber:
              description: Each chunk has 2 masters and 2 replicas. This field is
                used to specify node number of the cluster.
              format: int32
              type: integer
          required:
          - chunkNumber
          type: object
        status:
          description: UndermoonStatus defines the observed state of Undermoon
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
