apiVersion: undermoon.operator.api/v1alpha1
kind: Undermoon
metadata:
  name: example-undermoon
spec:
  clusterName: example-cluster
  chunkNumber: 1
  maxMemory: 32  # in MBs
  activeRedirection: false
  proxyThreads: 2
  undermoonImage: localhost:5000/undermoon_test
  undermoonImagePullPolicy: IfNotPresent
  redisImage: redis:5.0.9
