apiVersion: apps/v1
kind: Deployment
metadata:
  name: undermoon-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: undermoon-operator
  template:
    metadata:
      labels:
        name: undermoon-operator
    spec:
      serviceAccountName: undermoon-operator
      containers:
        - name: undermoon-operator
          # Replace this with the built image name
          image: localhost:5000/undermoon-operator:v0.0.1
          command:
          - undermoon-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "undermoon-operator"
