# Default values for undermoon-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cluster:
  clusterName: example-undermoon
  chunkNumber: 1
  maxMemory: 32  # in MBs
  port: 5299
  activeRedirection: false

image:
  undermoonImage: localhost:5000/undermoon_test
  undermoonImagePullPolicy: IfNotPresent
  redisImage: redis:5.0.9

nameOverride: ""
fullnameOverride: ""
